services:
  api:
    container_name: nest-docker-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    networks:
      - network-backend

networks:
  network-backend:
    driver: bridge
