services:
  api:
    container_name: nest-docker-api
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - PORT
      - SECRET_KEY
    ports:
      - 3001:3001
    networks:
      - network-backend

networks:
  network-backend:
    driver: bridge
