name: CD

on:
  workflow_run:
    workflows: ['CI']
    branches: ['main']
    types: 
      - requested

env:
  PORT: ${{ secrets.PORT }}
  SECRET_KEY: ${{ secrets.SECRET_KEY }}

jobs:
  deploy:
    name: deploy
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy docker-compose stack
        run: docker compose up -d --build

      - name: Prune Docker system
        run: docker system prune -af
